# Generated by Django 3.0.7 on 2020-08-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_address_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='house_no',
        ),
        migrations.AddField(
            model_name='address',
            name='HouseNum',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
