# Generated by Django 3.0.7 on 2020-08-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20200805_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
